// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owcvucdpcsttbcdxdoqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93Y3Z1Y2RwY3N0dGJjZHhkb3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxNDA1OTcsImV4cCI6MjA1MDcxNjU5N30.902IHfnue72f3obxWvQw_xkNp8w1jZpgbU5E8RW0voo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);